
# serverless.yml

service: maistodos
provider:
  name: aws
  stage: beta
  region: us-east-1
  runtime: python3.11

functions:
  - app:
      handler: wsgi_handler.handler
      events:
        - httpApi:
            path: '*'
      timeout: 30

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - .idea/**
    - .git/**
    - .github/**
    - .serverless/**
    - .cache/**
    - __pycache__/**
    - node_modules/**

custom:
  pythonRequirements:
#    dockerizePip: true
    useDownloadCache: false
    useStaticCache: false
    pipCmdExtraArgs: ['--platform', 'manylinux2014_x86_64', '--only-binary=:all:']
  wsgi:
    app: maistodos.wsgi.application
