# Generated by Django 4.2.3 on 2023-07-31 18:11

import django.core.validators
import django_cryptography.fields
from django.db import migrations, models

import credit_card_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exp_date", models.DateField()),
                ("holder", models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                (
                    "_number",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            db_column="number",
                            max_length=16,
                            validators=[credit_card_app.models.credid_card_number_validator],
                        )
                    ),
                ),
                (
                    "cvv",
                    models.CharField(
                        blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(3)]
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
            ],
        ),
    ]
